# fly.toml app configuration file generated for minesweeper-web on 2025-08-04T23:15:27-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'minesweeper-web'
primary_region = 'sjc'

[build]

[env]
  LOG_LEVEL = 'info'
  NODE_ENV = 'production'
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/api/health'

[[vm]]
  size = 'shared-cpu-1x'
